blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/itachi-re/bootanimation-template/discussions
    about: For general questions, use Discussions instead of an issue.
